In [1]:
import copy
import math
import pandas
from matplotlib import pyplot as plt
from py_ballisticcalc import TableG7, TableG1
from py_ballisticcalc import Ammo, Atmo, Wind
from py_ballisticcalc import Weapon, Shot, Calculator
from py_ballisticcalc import PreferredUnits
from py_ballisticcalc.drag_model import *
from py_ballisticcalc.unit import *
from py_ballisticcalc.trajectory_calc import *

print("Default units:\n"+str(PreferredUnits))  # Print default units

INFO:py_balcalc:Library running in pure python mode. For better performance install 'py_ballisticcalc.exts' package

Default units:
angular = degree
distance = yard
velocity = fps
pressure = inHg
temperature = fahrenheit
diameter = inch
length = inch
weight = grain
adjustment = mil
drop = inch
energy = foot-pound
ogw = pound
sight_height = inch
target_height = inch
twist = inch

In [2]:
zero = Shot(weapon=Weapon(sight_height=2), ammo=Ammo(DragModel(0.22, TableG7), mv=Velocity.FPS(2600)), relative_angle=Angular.Mil(1.33))
calc = Calculator()
zero_distance = Distance.Yard(100)
traj = calc.fire(zero, trajectory_range=zero_distance)
traj.dataframe(True).drop(['height', 'look_distance', 'density_factor', 'energy', 'ogw', 'flag'], axis=1).set_index('distance')

Running Euler integration...

,time,velocity,mach,target_drop,drop_adj,windage,windage_adj,angle,drag
distance,,,,,,,,,
0.0 yd,0.000 s,2600.0 ft/s,2.33 mach,-2.0 inch,0.000 mil,0.0 inch,0.000 mil,0.0748 °,0.000
10.0 yd,0.012 s,2579.4 ft/s,2.31 mach,-1.6 inch,-4.403 mil,0.0 inch,0.000 mil,0.0666 °,0.685
20.0 yd,0.023 s,2558.9 ft/s,2.29 mach,-1.2 inch,-1.647 mil,0.0 inch,0.000 mil,0.0582 °,0.682
30.0 yd,0.035 s,2538.5 ft/s,2.27 mach,-0.8 inch,-0.779 mil,0.0 inch,0.000 mil,0.0497 °,0.679
40.0 yd,0.047 s,2518.2 ft/s,2.26 mach,-0.5 inch,-0.383 mil,0.0 inch,0.000 mil,0.0410 °,0.676
50.0 yd,0.059 s,2497.9 ft/s,2.24 mach,-0.3 inch,-0.176 mil,0.0 inch,0.000 mil,0.0322 °,0.673
60.0 yd,0.071 s,2477.8 ft/s,2.22 mach,-0.1 inch,-0.064 mil,0.0 inch,0.000 mil,0.0233 °,0.670
70.0 yd,0.083 s,2457.7 ft/s,2.20 mach,-0.0 inch,-0.008 mil,0.0 inch,0.000 mil,0.0142 °,0.667
80.0 yd,0.095 s,2437.7 ft/s,2.18 mach,0.0 inch,0.015 mil,0.0 inch,0.000 mil,0.0050 °,0.664
90.0 yd,0.108 s,2417.9 ft/s,2.17 mach,0.0 inch,0.013 mil,0.0 inch,0.000 mil,-0.0044 °,0.661
100.0 yd,0.120 s,2398.1 ft/s,2.15 mach,-0.0 inch,-0.004 mil,0.0 inch,0.000 mil,-0.0139 °,0.658

In [3]:
set_calcMethod(CalcMethod.RK_dt)
zero = Shot(weapon=Weapon(sight_height=2), ammo=Ammo(DragModel(0.22, TableG7), mv=Velocity.FPS(2600)), relative_angle=Angular.Mil(1.33))
calc = Calculator()
zero_distance = Distance.Yard(100)
traj = calc.fire(zero, trajectory_range=zero_distance)
traj.dataframe(True).drop(['height', 'look_distance', 'density_factor', 'energy', 'ogw', 'flag'], axis=1).set_index('distance')

Running RK4 dt integration...

,time,velocity,mach,target_drop,drop_adj,windage,windage_adj,angle,drag
distance,,,,,,,,,
0.0 yd,0.000 s,2600.0 ft/s,2.33 mach,-2.0 inch,0.000 mil,0.0 inch,0.000 mil,0.0748 °,0.000
10.0 yd,0.012 s,2579.4 ft/s,2.31 mach,-1.6 inch,-4.401 mil,0.0 inch,0.000 mil,0.0666 °,0.685
20.0 yd,0.023 s,2558.9 ft/s,2.29 mach,-1.2 inch,-1.646 mil,0.0 inch,0.000 mil,0.0582 °,0.682
30.0 yd,0.035 s,2538.5 ft/s,2.27 mach,-0.8 inch,-0.777 mil,0.0 inch,0.000 mil,0.0497 °,0.679
40.0 yd,0.047 s,2518.2 ft/s,2.26 mach,-0.5 inch,-0.381 mil,0.0 inch,0.000 mil,0.0410 °,0.676
50.0 yd,0.059 s,2497.9 ft/s,2.24 mach,-0.3 inch,-0.175 mil,0.0 inch,0.000 mil,0.0322 °,0.673
60.0 yd,0.071 s,2477.8 ft/s,2.22 mach,-0.1 inch,-0.063 mil,0.0 inch,0.000 mil,0.0233 °,0.670
70.0 yd,0.083 s,2457.7 ft/s,2.20 mach,-0.0 inch,-0.006 mil,0.0 inch,0.000 mil,0.0142 °,0.667
80.0 yd,0.095 s,2437.8 ft/s,2.18 mach,0.0 inch,0.016 mil,0.0 inch,0.000 mil,0.0050 °,0.664
90.0 yd,0.108 s,2417.9 ft/s,2.17 mach,0.0 inch,0.015 mil,0.0 inch,0.000 mil,-0.0044 °,0.661
100.0 yd,0.120 s,2398.1 ft/s,2.15 mach,-0.0 inch,-0.003 mil,0.0 inch,0.000 mil,-0.0139 °,0.658

In [4]:
set_calcMethod(CalcMethod.RK_dx)
zero = Shot(weapon=Weapon(sight_height=2), ammo=Ammo(DragModel(0.22, TableG7), mv=Velocity.FPS(2600)), relative_angle=Angular.Mil(1.33))
calc = Calculator()
zero_distance = Distance.Yard(100)
traj = calc.fire(zero, trajectory_range=zero_distance)
traj.dataframe(True).drop(['height', 'look_distance', 'density_factor', 'energy', 'ogw', 'flag'], axis=1).set_index('distance')

Running RK4 dx integration...

,time,velocity,mach,target_drop,drop_adj,windage,windage_adj,angle,drag
distance,,,,,,,,,
0.0 yd,0.000 s,2600.0 ft/s,2.33 mach,-2.0 inch,0.000 mil,0.0 inch,0.000 mil,0.0748 °,0.000
10.0 yd,0.012 s,2579.4 ft/s,2.31 mach,-1.6 inch,-4.401 mil,0.0 inch,0.000 mil,0.0666 °,0.685
20.0 yd,0.023 s,2558.9 ft/s,2.29 mach,-1.2 inch,-1.646 mil,0.0 inch,0.000 mil,0.0582 °,0.682
30.0 yd,0.035 s,2538.5 ft/s,2.27 mach,-0.8 inch,-0.777 mil,0.0 inch,0.000 mil,0.0497 °,0.679
40.0 yd,0.047 s,2518.2 ft/s,2.26 mach,-0.5 inch,-0.381 mil,0.0 inch,0.000 mil,0.0410 °,0.676
50.0 yd,0.059 s,2497.9 ft/s,2.24 mach,-0.3 inch,-0.175 mil,0.0 inch,0.000 mil,0.0322 °,0.673
60.0 yd,0.071 s,2477.8 ft/s,2.22 mach,-0.1 inch,-0.063 mil,0.0 inch,0.000 mil,0.0233 °,0.670
70.0 yd,0.083 s,2457.7 ft/s,2.20 mach,-0.0 inch,-0.006 mil,0.0 inch,0.000 mil,0.0142 °,0.667
80.0 yd,0.095 s,2437.8 ft/s,2.18 mach,0.0 inch,0.016 mil,0.0 inch,0.000 mil,0.0050 °,0.664
90.0 yd,0.108 s,2417.9 ft/s,2.17 mach,0.0 inch,0.015 mil,0.0 inch,0.000 mil,-0.0044 °,0.661
100.0 yd,0.120 s,2398.1 ft/s,2.15 mach,-0.0 inch,-0.003 mil,0.0 inch,0.000 mil,-0.0139 °,0.658